/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theevansfingers;

import database.Database;
import java.util.HashMap;
import java.util.List;
import logic.Courses;
import logic.HoldVariables;

/**
 *
 * @author Paulous
 */
public class StartCourse extends javax.swing.JPanel {
      private HashMap<String, String> hash;

    /**
     * Creates new form StartCourse
     */
    public StartCourse() {
        initComponents();
    }
    
    private void loadCombo(){
        Database db = new Database();
        List<Courses> courses = db.getAllCourses();
           hash = new HashMap<>();
        
        for(int i=0; i<courses.size();i++){
            String courseName = courses.get(i).getCourseName();
            String courseCodes = courses.get(i).getCourseCode();
            
            courseCode.addItem(courseCodes);
            hash.put(courseCodes, courseName);
            System.out.print(courseName + " Nothing");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseCode = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        courseLecturer = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setName("Start a Course"); // NOI18N

        courseCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ICT 401", "ICT 487", "ICT 345" }));

        jLabel1.setText("Course Code:");

        jLabel2.setText("Course Lecturer");

        courseLecturer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dr. Simfukwe", "Dr. Chembe", "Dr. Zimba" }));

        jButton1.setText("Start Course");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(courseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(courseLecturer, 0, 106, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(courseLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HoldVariables.courseCode = courseCode.getSelectedItem().toString();
        HoldVariables.courseLecturer = courseLecturer.getSelectedItem().toString();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox courseCode;
    private javax.swing.JComboBox courseLecturer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
